### ISSUE TITLE
error with container checks

### ISSUE THREAD

**Issue by njordr** [Nitro/sidecar#28]
Hi.

Trying sidecar another issue raised. Don't know if something I misunderstood, but it's not simple to search on the web for the type of error:

```
time="2018-09-09T19:11:22Z" level=warning msg="Adding check for service mysql:5.7@sha256:1d8f471c7e2929ee1e2bfbc1d16fc8afccd2e070afed24805487e726ce601a6d (id: 574d6ce4048a) failed. Got check type: , check args: ." 
```

**Comment by njordr** [comment]
Sorry, I forgot to configure the labels :(

**Comment by mihaitodor** [comment]
Yes, indeed, that error message is completely silly. I shall fix it now.

Sidecar supports 3 types of health checks (see [Readme](https://github.com/Nitro/sidecar/blob/master/README.md)) (`HttpGet`, `External` and `AlwaysSuccessful`). By default, it will try to find the first exposed TCP port (if any) and run HTTP GET on the `/version` endpoint to determine the health of the service. If there is no TCP port exposed, then it will fall back to `AlwaysSuccessful` (see [here](https://github.com/Nitro/sidecar/blob/906372616ca1dac8143c9cc34f98a0814bcda10c/healthy/service_bridge.go#L50)). For testing purposes, the simplest thing is to use the label `HealthCheck =AlwaysSuccessful`.
